# Site settings
title: Masato Lin
email: linmasato16@gmail.com
description: > # keep this and put description below
  Programmer and Designer
url: "https://masatolin.github.io/" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/masatolin"
github_username: masatolin
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
